name: Golang Testing

on:
  workflow_call:

jobs:
  test:
    name: Unit Tests
    strategy:
      matrix:
        go-version:
        - 1.20.x
        platform:
        - ubuntu-latest

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Test
      run: go test ./... -v -cover -race
