name: Rust

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - run: cargo fmt --check
    - run: cargo clippy --all-features --all-targets --no-deps
    - run: cargo test
    - run: cargo build --all-features --release
