name: Rust CI

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo clippy --no-deps --all-targets --all-features
    - name: Test
      run: cargo test
    - name: Build
      run: cargo build --release
